project:
  type: website
  output-dir: docs

website:
  title: "vbfelix"
  page-footer:
    left: "Blog made with [Quarto](https://quarto.org/), by [Vinícius Félix](https://github.com/vbfelix/vbfelix.github.io). License: [CC BY-SA 2.0](https://creativecommons.org/licenses/by-sa/2.0/)."
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - publications.qmd
      - talks.qmd
      - icon: file-earmark-person
        href: https://drive.google.com/file/d/1WRmTpVTSztHxFZErdoj6qDvS1GAcjKey/view?usp=sharing      
      - icon: github
        href: https://github.com/vbfelix
      - icon: linkedin
        href: https://www.linkedin.com/in/vin%C3%ADcius-f%C3%A9lix-962010140/
      - icon: stack-overflow
        href: https://stackoverflow.com/users/9696037/vin%c3%adcius-f%c3%a9lix  


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

