---
title: "About"
---

Since 2013, I've been working with data analysis. During my studies in graduation, I focused on time-series, geostatistics, and data visualization. Also, I was one the founders of the junior enterprise Estats Consultoria, where I worked as Marketing Director and President besides acting as a data analyst in projects.

In 2016, I co-founded a data consulting firm (H0 Consultoria) with a partner, and we worked on over 350 scientific studies and over 40 surveys for businesses. Our job entailed assisting to maximize the use of statistics, from sample design to analysis, and sometimes even training others to use the techniques themselves.

In 2020, I was invited to establish and develop the data team within the Research & Development (R&D) department of GA, a brazilian animal science tech firm. In 2021, I was promoted to head of R&D, where I was responsible not just for the data, but also for the software development team.

GA merged with Intergado in 2022, a company that produces hardware for automating data collecting with accuracy in order to offer better actions through data science. Now, as the Strategy Manager for this new company, I oversee the implementation of corporate strategy across all products, monitoring and mapping project progress, identifying risks, and liaising between technical and non-technical teams to align priorities and goals.
