<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.313">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Vinícius Félix">
<meta name="dcterms.date" content="2023-07-30">

<title>vbfelix - An intro to Logistic Regression</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../..//images/favicon/favicon-32x32.png" rel="icon" type="image/png">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">vbfelix</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html">
 <span class="menu-text">Blog</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../header-about.html">
 <span class="menu-text">About me</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../header-publications.html">
 <span class="menu-text">Publications</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../header-certifications.html">
 <span class="menu-text">Certifications</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../header-talks.html">
 <span class="menu-text">Events</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/vbfelix"><i class="bi bi-github" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/vin%C3%ADcius-f%C3%A9lix-962010140/"><i class="bi bi-linkedin" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://stackoverflow.com/users/9696037/vin%c3%adcius-f%c3%a9lix"><i class="bi bi-stack-overflow" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://vbfelix.github.io/relper"><i class="bi bi-box-seam" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">An intro to Logistic Regression</h1>
                                <div class="quarto-categories">
                <div class="quarto-category">Intro to</div>
                <div class="quarto-category">Probability</div>
                <div class="quarto-category">Theory</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Vinícius Félix </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">July 30, 2023</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#application" id="toc-application" class="nav-link" data-scroll-target="#application">Application</a>
  <ul class="collapse">
  <li><a href="#odds-ratios" id="toc-odds-ratios" class="nav-link" data-scroll-target="#odds-ratios">Odds ratios</a></li>
  </ul></li>
  <li><a href="#considerations" id="toc-considerations" class="nav-link" data-scroll-target="#considerations">Considerations</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">




<div class="cell">

</div>
<p>In this post of the series <strong>Intro to</strong>, I’ll give an introduction to the Logistic Regression.</p>
<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>A linear model (LM) is given by:</p>
<p><span id="eq-linear-model"><span class="math display">\[
Y_i = \beta_0 + \beta_1x_1 + ...+\beta_nx_n + \varepsilon_i,
\tag{1}\]</span></span></p>
<p>where:</p>
<ul>
<li><p><span class="math inline">\(Y_i\)</span> is the response variable;</p></li>
<li><p><span class="math inline">\(\beta_0\)</span> is the intercept;</p></li>
<li><p><span class="math inline">\(\beta_1\)</span> is the slope coefficient of the explanatory variable <span class="math inline">\(x_1\)</span> ;</p></li>
<li><p><span class="math inline">\(\beta_n\)</span> is the slope coefficient of theexplanatory variable <span class="math inline">\(x_n\)</span> ;</p></li>
<li><p><span class="math inline">\(\varepsilon_i\)</span> is the error term.</p></li>
</ul>
<p>Given that the response variable is a numeric continuous variable, a linear model establishes a linear relationship between the explanatory variables and the response variable.</p>
<p>We have a flexible generalization of ordinary linear regression called generalized linear model (GLM) to extend the application of linear models to other scenarios, such as going beyond the normal distribution.</p>
<p>A GLM generalizes linear regression by allowing the linear model to be linked to the response variable via a link function and allowing the magnitude of the variance of each measurement to be a function of its predicted value.</p>
<p>In a LM we have that,</p>
<p><span id="eq-expected-value"><span class="math display">\[E(Y_i)= \mu_i, \tag{2}\]</span></span></p>
<p>where:</p>
<ul>
<li><p><span class="math inline">\(E(.)\)</span> is the expected value,</p></li>
<li><p><span class="math inline">\(\mu_i\)</span> is the expected value of <span class="math inline">\(Y_i\)</span>.</p></li>
</ul>
<p>But with a GLM we have that,</p>
<p><span id="eq-link-function"><span class="math display">\[G(\mu_i) = \beta_0 + \beta_1x_1 + ...+\beta_nx_n, \tag{3}\]</span></span> where:</p>
<ul>
<li><span class="math inline">\(\beta_0 + \beta_1x_1 + ...+\beta_nx_n\)</span> is the linear predictor;</li>
<li><span class="math inline">\(G\)</span> is a link funtion, that transforms the expected value of the response variable to the linear predictor.</li>
</ul>
<p>A logistic regression is a GLM where the link function is given by a logit function, given by:</p>
<p><span id="eq-logit-function"><span class="math display">\[\log \left(\frac{p}{1-p}\right), \tag{4}\]</span></span> where:</p>
<ul>
<li><span class="math inline">\(p\)</span> is the probability of the outcome of <span class="math inline">\(Y_i = 1\)</span>.</li>
</ul>
<p>So logistic regression is a type of model technique used in situations where the response variable’s outcome is binary (0 or 1).</p>
<p>The logit function’s behavior for a probability is shown below.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-1-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>We can see that for a proability lower than 0.5, the logit will be negative. Besides that, we can also see that the logit function is actually the logarithm of the odds <span class="math inline">\(\frac{p}{1-p}\)</span>.</p>
</section>
<section id="application" class="level1">
<h1>Application</h1>
<blockquote class="blockquote">
<p><strong>Disclaimer:</strong> because the goal of this article is to introduce logistics regression, some topics such as classification, accuracy, goodness of fit, intercept, and others will not be covered.</p>
</blockquote>
<p>To apply in a real-world scenario, we will use the data set of the Titanic passengers <span class="citation" data-cites="datasets">(<a href="#ref-datasets" role="doc-biblioref">2021</a>)</span>, which consists of 2,201 passengers with the following characteristics:</p>
<ul>
<li><p><strong>Class</strong>: Crew, 3rd, 2nd and 1st;</p></li>
<li><p><strong>Sex</strong>: Male and Female;</p></li>
<li><p><strong>Age</strong>: Child and Adult;</p></li>
<li><p><strong>Survived</strong>: No and Yes.</p></li>
</ul>
<p>The limited availability of lifeboats and the overall evacuation procedures influenced the decision-making process for which Titanic passengers were saved during the disaster. There were not enough lifeboats to accommodate all of the passengers and crew when the Titanic collided with an iceberg and began to sink.</p>
<p>The Titanic only had 20 lifeboats, with a total capacity of roughly half the number of passengers.</p>
<div class="cell">

</div>
<p>Before we begin modeling, let’s take a look at our data.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The majority of passengers (95.05%) were adults, with children accounting for a smaller proportion (4.95%). The crew class had the most members (40.21%), followed by the third class (32.08%), first class (14.77%), and second class (12.95%). Male passengers made up 78.65% of the total, while females made up 21.35%.</p>
<p>According to the survival rate, 32.30% of passengers survived the disaster, while 67.70% did not.</p>
<p>This graph sheds light on the demographics of the Titanic passengers, but our main goal here is to try to discover survival patterns based on those characteristics, so let’s first look at the survival rate for each level and variable.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Even though they made up less than 5% of the passengers, children had a higher survival rate (52.29%).</p>
<p>First-class passengers had the highest survival rate (62.46%), followed by second-class passengers (41.40%), indicating that the survival rate of class had a hierarchical behavior.</p>
<p>Female passengers had a significantly higher survival rate (73.19%) than male passengers (21.20%).</p>
<p>These findings highlight the varying effects of age, ticket class, and gender on survival during the Titanic disaster, with children, first-class passengers, and female passengers having a better chance of survival, despite not constituting the majority of passengers.</p>
<p>The evacuation procedure followed the “<em>women and children firs</em>t” policy, which prioritized women, children, and some crew members were exempt from this policy.</p>
<p>There were exceptions, with some men allowed on lifeboats if space was available or if they boarded without opposition. Confusion and miscommunication resulted in inefficient use of lifeboat spaces. As a result, many passengers, particularly lower-class men, were left on the sinking ship, risking their lives.</p>
<p>Now, we will try to consider all this factors in a single model to understand the effect of each one in the survival of this tragedy.</p>
<div class="cell">

</div>
<div class="cell">
<div class="cell-output-display">

<table>
 <thead>
  <tr>
   <th style="text-align:center;"> term </th>
   <th style="text-align:center;"> estimate </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:center;"> ageAdult </td>
   <td style="text-align:center;"> -1.0615 </td>
  </tr>
  <tr>
   <td style="text-align:center;"> class3rd </td>
   <td style="text-align:center;"> -0.9201 </td>
  </tr>
  <tr>
   <td style="text-align:center;"> class2nd </td>
   <td style="text-align:center;"> -0.1604 </td>
  </tr>
  <tr>
   <td style="text-align:center;"> class1st </td>
   <td style="text-align:center;"> 0.8577 </td>
  </tr>
  <tr>
   <td style="text-align:center;"> sexFemale </td>
   <td style="text-align:center;"> 2.4201 </td>
  </tr>
</tbody>
</table>

</div>
</div>
<p>First of all we see the estimate of the coefficients (<span class="math inline">\(\beta_i\)</span>) for each variable, and because all variables are categoricals, we have a baseline for each one that serves as the reference level. But what do these figures mean?</p>
<section id="odds-ratios" class="level2">
<h2 class="anchored" data-anchor-id="odds-ratios">Odds ratios</h2>
<p>To better understand the practical implications of the coefficients, we can apply the coefficients’ exponential to obtain the odds ratios.</p>
<hr>
<dl>
<dt>Odds ratio (OR)</dt>
<dd>
<p><em>The odds ratio indicates how much the outcome odds change for a one-unit increase in the predictor variable (for continuous predictors) or when moving from one category to another (for categorical predictors).</em></p>
</dd>
</dl>
<hr>
<p>Here is why, let’s say we have two logit’s (<span class="math inline">\(p_1\)</span> and <span class="math inline">\(p_2\)</span>), and we will subtract one from another, so:</p>
<p><span id="eq-logit-to-log-or"><span class="math display">\[
\begin{align}
\mathrm{logit}_{p_1} - \mathrm{logit}_{p_2}
&amp;= \log \left( \frac{p_1}{1-p_1}\right) - \log \left( \frac{p_2}{1-p_2}\right)\\
&amp;= \log \left( \frac{p_1}{1-p_1}\middle/ \frac{p_2}{1-p_2}\right).\\
\end{align}
\tag{5}\]</span></span></p>
<p>So the difference between two logit functions is the logarithm of an odds ratio, which means that we can get the OR by applying an exponential function to the coefficients of a logistic model.</p>
<div class="cell">
<div class="cell-output-display">

<table>
 <thead>
  <tr>
   <th style="text-align:center;"> term </th>
   <th style="text-align:center;"> estimate </th>
   <th style="text-align:center;"> OR </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:center;"> ageAdult </td>
   <td style="text-align:center;"> -1.0615 </td>
   <td style="text-align:center;"> 0.3459 </td>
  </tr>
  <tr>
   <td style="text-align:center;"> class3rd </td>
   <td style="text-align:center;"> -0.9201 </td>
   <td style="text-align:center;"> 0.3985 </td>
  </tr>
  <tr>
   <td style="text-align:center;"> class2nd </td>
   <td style="text-align:center;"> -0.1604 </td>
   <td style="text-align:center;"> 0.8518 </td>
  </tr>
  <tr>
   <td style="text-align:center;"> class1st </td>
   <td style="text-align:center;"> 0.8577 </td>
   <td style="text-align:center;"> 2.3577 </td>
  </tr>
  <tr>
   <td style="text-align:center;"> sexFemale </td>
   <td style="text-align:center;"> 2.4201 </td>
   <td style="text-align:center;"> 11.2465 </td>
  </tr>
</tbody>
</table>

</div>
</div>
<p>Now that we have the OR of each level compared to their respective baseline (reference level), we can interpret them by looking at their magnitude, where if is:</p>
<ul>
<li><p>equal to 1, it means that the predictor variable has no effect on the outcome odds;</p></li>
<li><p>greater than 1, it indicates an increase in the odds of the outcome;</p></li>
<li><p>less than 1, it indicates a decrease in the odds of the outcome.</p></li>
</ul>
<p>Let’s take the example of an Adult in the model, it has a 34,59% chance to survive in comparison to a child (reference level), that means that being an adult reduces the odds of the outcome by approximately 65.4%.</p>
<p>So we can easily measure the impact by doing OR-1; if negative, the odds of the outcome are reduced; if positive, the odds of the outcome are increased.</p>
<div class="cell">
<div class="cell-output-display">

<table>
 <thead>
  <tr>
   <th style="text-align:center;"> term </th>
   <th style="text-align:center;"> estimate </th>
   <th style="text-align:center;"> OR </th>
   <th style="text-align:center;"> OR-1 </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:center;"> ageAdult </td>
   <td style="text-align:center;"> -1.0615 </td>
   <td style="text-align:center;"> 0.3459 </td>
   <td style="text-align:center;"> -0.6541 </td>
  </tr>
  <tr>
   <td style="text-align:center;"> class3rd </td>
   <td style="text-align:center;"> -0.9201 </td>
   <td style="text-align:center;"> 0.3985 </td>
   <td style="text-align:center;"> -0.6015 </td>
  </tr>
  <tr>
   <td style="text-align:center;"> class2nd </td>
   <td style="text-align:center;"> -0.1604 </td>
   <td style="text-align:center;"> 0.8518 </td>
   <td style="text-align:center;"> -0.1482 </td>
  </tr>
  <tr>
   <td style="text-align:center;"> class1st </td>
   <td style="text-align:center;"> 0.8577 </td>
   <td style="text-align:center;"> 2.3577 </td>
   <td style="text-align:center;"> 1.3577 </td>
  </tr>
  <tr>
   <td style="text-align:center;"> sexFemale </td>
   <td style="text-align:center;"> 2.4201 </td>
   <td style="text-align:center;"> 11.2465 </td>
   <td style="text-align:center;"> 10.2465 </td>
  </tr>
</tbody>
</table>

</div>
</div>
<p>As previously stated, being an adult reduced the odds of the outcome by approximately 65.4% when compared to being a child.</p>
<p>Passengers in the third class have their odds reduced by approximately 60.2% when compared to the crew, while passengers in the second class have their odds reduced by approximately 14.8%. Being in the first class, on the other hand, increases the odds of the outcome by approximately 135.8%.</p>
<p>Sex had the greatest impact, with being female increased the odds by approximately 1,024.7% when compared to being male.</p>
</section>
</section>
<section id="considerations" class="level1">
<h1>Considerations</h1>
<p>Logistic regression is an effective method for modeling binary phenomena.</p>
<p>Its ease of use and interpretability make it an appealing option for estimating probabilities and understanding the relationships between predictors and odds.</p>
<p>However, it is important to note that logistic regression assumes independence and linearity, which limits its applicability to complex nonlinear relationships and dependent data. When using logistic regression in practical scenarios, it is critical to carefully consider these benefits and drawbacks, especially when using to predict/classify something.</p>



</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" role="doc-bibliography">
<div id="ref-datasets" class="csl-entry" role="doc-biblioentry">
R Core Team. 2021. <span>“R: A Language and Environment for Statistical Computing.”</span> <a href="https://www.R-project.org/">https://www.R-project.org/</a>.
</div>
</div></section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">Blog made with <a href="https://quarto.org/">Quarto</a>, by <a href="https://github.com/vbfelix/vbfelix.github.io">Vinícius Félix</a>. License: <a href="https://creativecommons.org/licenses/by-sa/2.0/">CC BY-SA 2.0</a>.</div>   
  </div>
</footer>



</body></html>